# Generated by Django 5.0.6 on 2026-06-03 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar')], default='vocab', max_length=12)),
                ('language', models.CharField(blank=True, default='', max_length=4)),
                ('front', models.TextField()),
                ('back', models.TextField(blank=True, default='')),
                ('reading', models.TextField(blank=True, default='')),
                ('article', models.CharField(choices=[('none', '—'), ('der', 'der (m, blue)'), ('die', 'die (f, red)'), ('das', 'das (n, green)'), ('plural', 'die (pl)')], default='none', max_length=8)),
                ('example', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('table', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning'), ('suspended', 'Suspended')], default='new', max_length=12)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease', models.PositiveIntegerField(default=2500)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_leech', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('state_before', models.CharField(max_length=12)),
                ('state_after', models.CharField(max_length=12)),
                ('interval_before', models.PositiveIntegerField(default=0)),
                ('interval_after', models.PositiveIntegerField(default=0)),
                ('ease_before', models.PositiveIntegerField(default=0)),
                ('ease_after', models.PositiveIntegerField(default=0)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('prev_snapshot', models.JSONField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'state', 'due'], name='cards_card_deck_id_741877_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user', '-reviewed_at'], name='cards_revie_user_id_3379a8_idx'),
        ),
    ]
