# Generated by Django 5.0.6 on 2026-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='genders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
