# Generated by Django 5.0.6 on 2026-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
