# Generated by Django 5.0.6 on 2026-06-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='direction',
            field=models.CharField(choices=[('forward', 'Forward (term → meaning)'), ('reverse', 'Reverse (meaning → term)')], default='forward', max_length=8),
        ),
        migrations.AddField(
            model_name='card',
            name='reverse_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverses', to='cards.card'),
        ),
    ]
