# Generated by Django 5.0.6 on 2026-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
