# Generated by Django 5.0.6 on 2026-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_conjugations_verb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mnemonic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
