# Generated by Django 5.0.6 on 2026-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_mnemonic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition')], default='vocab', max_length=12),
        ),
    ]
