# Generated by Django 5.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_telegramlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='default_language',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='default_back_language',
            field=models.CharField(default='English', max_length=32),
        ),
        migrations.CreateModel(
            name='PendingTelegramCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=4)),
                ('front', models.CharField(max_length=200)),
                ('back', models.TextField(blank=True)),
                ('reading', models.CharField(blank=True, max_length=200)),
                ('article', models.CharField(default='none', max_length=8)),
                ('plural', models.CharField(blank=True, max_length=200)),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
