# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_telegram_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtelegramcard',
            name='awaiting_field',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
