# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pendingtelegramcard_awaiting_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtelegramcard',
            name='translation_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pendingtelegramcard',
            name='pronunciation_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
