# Generated by Django 5.0.6 on 2026-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_pendingtelegramcard_choice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtelegramcard',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
