# Generated by Django 5.0.6 on 2026-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pendingtelegramcard_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtelegramcard',
            name='card_type',
            field=models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar'), ('verb', 'Verb')], default='vocab', max_length=12),
        ),
    ]
