# Generated by Django 5.0.6 on 2026-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_pendingtelegramcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='pending_lookup_card_type',
            field=models.CharField(blank=True, choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar'), ('verb', 'Verb')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='pending_lookup_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='pending_lookup_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
