# Generated by Django 5.0.6 on 2026-08-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_telegramlink_pending_lookup_card_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPollerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField(default=0)),
            ],
        ),
    ]
