# Generated by Django 5.0.6 on 2026-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_telegrampollerstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtelegramcard',
            name='card_type',
            field=models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition')], default='vocab', max_length=12),
        ),
        migrations.AlterField(
            model_name='telegramlink',
            name='pending_lookup_card_type',
            field=models.CharField(blank=True, choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('grammar', 'Grammar'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition')], default='', max_length=12),
        ),
    ]
