# Generated by Django 5.0.6 on 2026-07-29 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionrequest_tx_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic_monthly', 'Basic · 1 month'), ('basic_quarterly', 'Basic · 3 months'), ('basic_yearly', 'Basic · 12 months'), ('pro_monthly', 'Pro · 1 month'), ('pro_quarterly', 'Pro · 3 months'), ('pro_yearly', 'Pro · 12 months')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='plan',
            field=models.CharField(choices=[('basic_monthly', 'Basic · 1 month'), ('basic_quarterly', 'Basic · 3 months'), ('basic_yearly', 'Basic · 12 months'), ('pro_monthly', 'Pro · 1 month'), ('pro_quarterly', 'Pro · 3 months'), ('pro_yearly', 'Pro · 12 months')], max_length=16),
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'day'], name='subscriptio_user_id_6a96c5_idx')],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
