# Generated by Django 5.0.6 on 2026-06-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('source_language', models.CharField(blank=True, default='', max_length=4)),
                ('translation_language', models.CharField(default='English', max_length=40)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('color', models.CharField(default='#4c6ef5', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('position', models.PositiveIntegerField(default=0)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='books.book')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='vocab', max_length=12)),
                ('front', models.TextField()),
                ('back', models.TextField(blank=True, default='')),
                ('reading', models.TextField(blank=True, default='')),
                ('article', models.CharField(default='none', max_length=8)),
                ('plural', models.CharField(blank=True, default='', max_length=120)),
                ('example', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('table', models.JSONField(blank=True, null=True)),
                ('genders', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='books.booklesson')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
