# Generated by Django 5.0.6 on 2026-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklesson',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
