# Generated by Django 5.0.6 on 2026-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_booklesson_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklesson',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booklesson',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
