# Generated by Django 5.0.6 on 2026-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booklesson_page_end_booklesson_page_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_lessons/'),
        ),
    ]
