# Generated by Django 5.0.6 on 2026-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookshare_bookshare_unique_book_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklesson',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
