# Generated by Django 5.0.6 on 2026-08-15 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelPurgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('cutoff_date', models.DateTimeField(blank=True, null=True)),
                ('reels_purged', models.PositiveIntegerField(default=0)),
                ('bytes_freed', models.BigIntegerField(default=0)),
                ('hard_delete', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(default='cron', max_length=80)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelsBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('month', models.CharField(blank=True, default='', max_length=7)),
                ('spent_this_month_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('default_results_limit', models.PositiveIntegerField(default=3)),
                ('default_retention_days', models.PositiveIntegerField(default=90)),
                ('alerts_sent', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Reels budget',
                'verbose_name_plural': 'Reels budget',
            },
        ),
        migrations.CreateModel(
            name='ReelsCostMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('reels_billed', models.PositiveIntegerField(default=0)),
                ('reels_new', models.PositiveIntegerField(default=0)),
                ('apify_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('storage_gb_month', models.FloatField(default=0)),
                ('storage_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ReelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('instagram', 'Instagram'), ('own', 'Our own')], default='instagram', max_length=12)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reel_avatars/')),
                ('language', models.CharField(default='de', max_length=4)),
                ('level', models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], default='', max_length=2)),
                ('topics', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_granted', models.BooleanField(default=False)),
                ('permission_note', models.CharField(blank=True, default='', max_length=240)),
                ('poll_interval_hours', models.PositiveIntegerField(default=24)),
                ('results_limit', models.PositiveIntegerField(default=3)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Blank = use the global default.', null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'username'],
            },
        ),
        migrations.CreateModel(
            name='ReelsStorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('stored_bytes', models.BigIntegerField(default=0)),
                ('reel_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='ReelFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apify_run_id', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped (budget)')], default='running', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_returned', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('estimated_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('triggered_by', models.CharField(default='cron', max_length=80)),
                ('error', models.TextField(blank=True, default='')),
                ('sources', models.ManyToManyField(blank=True, related_name='fetch_runs', to='reels.reelsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('url', models.URLField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('caption', models.TextField(blank=True, default='')),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('video', models.FileField(blank=True, null=True, upload_to='reels/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='reel_posters/')),
                ('video_bytes', models.BigIntegerField(default=0)),
                ('media_status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('failed', 'Failed'), ('purged', 'Purged')], default='pending', max_length=10)),
                ('media_purged_at', models.DateTimeField(blank=True, null=True)),
                ('media_error', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('language', models.CharField(default='de', max_length=4)),
                ('level', models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], default='', max_length=2)),
                ('topics', models.CharField(blank=True, default='', max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_evergreen', models.BooleanField(default=False)),
                ('pin_until', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='reels.reelsource')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reels.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['is_published', 'language', '-posted_at'], name='reels_reel_is_publ_30b356_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['media_status'], name='reels_reel_media_s_b7e8a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='reelview',
            constraint=models.UniqueConstraint(fields=('user', 'reel'), name='unique_reel_view'),
        ),
    ]
