# Generated by Django 5.0.6 on 2026-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reel',
            name='reels_reel_is_publ_30b356_idx',
        ),
        migrations.RenameField(
            model_name='reel',
            old_name='language',
            new_name='target_language',
        ),
        migrations.RenameField(
            model_name='reelsource',
            old_name='language',
            new_name='target_language',
        ),
        migrations.AddField(
            model_name='reel',
            name='base_language',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='reelsource',
            name='base_language',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['is_published', 'target_language', '-posted_at'], name='reels_reel_is_publ_bdaeff_idx'),
        ),
    ]
