# Generated by Django 5.0.6 on 2026-08-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckshare_deckshare_unique_deck_share'),
        ('reels', '0002_remove_reel_reels_reel_is_publ_30b356_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='cards_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reel',
            name='cards_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='linked_deck',
            field=models.ForeignKey(blank=True, help_text="Optional: a curated deck that 'make cards from this reel' imports as-is.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='decks.deck'),
        ),
    ]
