# Generated by Django 5.0.6 on 2026-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=4),
        ),
    ]
