# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_reminder_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='study_reminder_last_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
