# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_study_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_reminder_channel',
            field=models.CharField(choices=[('push', 'Push'), ('telegram', 'Telegram')], default='push', max_length=8),
        ),
    ]
