# Generated by Django 5.0.6 on 2026-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_study_reminder_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_digest_last_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
