# Generated by Django 5.0.6 on 2026-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_study_digest_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='known_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
