# Generated by Django 5.0.6 on 2026-06-03 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=80)),
                ('learning_steps', models.CharField(default='1 10', max_length=120)),
                ('relearning_steps', models.CharField(default='10', max_length=120)),
                ('graduating_interval', models.PositiveIntegerField(default=1)),
                ('easy_interval', models.PositiveIntegerField(default=4)),
                ('starting_ease', models.PositiveIntegerField(default=2500)),
                ('easy_bonus', models.PositiveIntegerField(default=1300)),
                ('hard_interval', models.PositiveIntegerField(default=1200)),
                ('interval_modifier', models.PositiveIntegerField(default=1000)),
                ('new_interval', models.PositiveIntegerField(default=0)),
                ('minimum_interval', models.PositiveIntegerField(default=1)),
                ('maximum_interval', models.PositiveIntegerField(default=36500)),
                ('new_per_day', models.PositiveIntegerField(default=20)),
                ('reviews_per_day', models.PositiveIntegerField(default=200)),
                ('leech_threshold', models.PositiveIntegerField(default=8)),
                ('leech_suspend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('language', models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('', 'Other')], default='', max_length=4)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='decks.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='decks.deckconfig')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('user', 'parent', 'name'), name='unique_deck_name_per_parent'),
        ),
    ]
